# Generated by Django 3.0.3 on 2020-05-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
