# Generated by Django 3.0.3 on 2020-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
