# Generated by Django 3.0.3 on 2020-05-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0002_auto_20200511_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingmode.Meeting')),
            ],
        ),
    ]
