# Generated by Django 3.0.3 on 2020-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0004_delete_meetingsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtranscript',
            name='author',
        ),
    ]
