# Generated by Django 3.0.3 on 2020-05-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0005_remove_meetingtranscript_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('summary', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_meeting', to='meetingmode.Meeting')),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingTranscript',
        ),
    ]
