# Generated by Django 3.0.3 on 2020-05-16 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetingmode', '0006_auto_20200515_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginfo',
            name='translated_summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
